### PR TITLE
ENH: Add parcellations (FS's annot files)

### PR DESCRIPTION
**Pull request by oesteban**
This (WIP) PR tries to propose some naming conventions. Entities:

- `atlas-`: to designate an *atlas* this parcellation is part
- `seg-`: a name for the particular parcellation (e.g., number of networks or "aparc")
- `scale-`: ~~(not used yet)~~ designates granularity (e.g., for seg-17n one could have several scales depending on the number of ROIs).

WDYT? @yasseraleman @effigies 

- TSV files are missing (will add when naming is more solid)
- [x] ~~@yasseraleman has a lot of other annot files that would go within this PR, once names look reasonable.~~ (added for left hemisphere and will do so for right with enough thumbs-up)

### CODE REVIEW

**Comment by oesteban** [comment]
@yasseraleman this is how this looks now:

```
tpl-fsaverage/
├── CHANGES
├── scripts
│   └── to_gii.py
├── template_description.json
├── tpl-fsaverage_dseg.tsv
├── tpl-fsaverage_hemi-L_den-10k_curv.shape.gii
├── tpl-fsaverage_hemi-L_den-10k_pial.surf.gii
├── tpl-fsaverage_hemi-L_den-10k_sphere.surf.gii
├── tpl-fsaverage_hemi-L_den-10k_sulc.shape.gii
├── tpl-fsaverage_hemi-L_den-10k_white.surf.gii
├── tpl-fsaverage_hemi-L_den-164k_atlas-Destrieux2005_dseg.label.gii
├── tpl-fsaverage_hemi-L_den-164k_atlas-Destrieux2009_dseg.label.gii
├── tpl-fsaverage_hemi-L_den-164k_atlas-Lausanne2018_scale-1_dseg.label.gii
├── tpl-fsaverage_hemi-L_den-164k_atlas-Lausanne2018_scale-2_dseg.label.gii
├── tpl-fsaverage_hemi-L_den-164k_atlas-Lausanne2018_scale-3_dseg.label.gii
├── tpl-fsaverage_hemi-L_den-164k_atlas-Lausanne2018_scale-4_dseg.label.gii
├── tpl-fsaverage_hemi-L_den-164k_atlas-Lausanne2018_scale-5_dseg.label.gii
├── tpl-fsaverage_hemi-L_den-164k_atlas-Sabuncu2011_dseg.label.gii
├── tpl-fsaverage_hemi-L_den-164k_atlas-Schaefer2018_seg-17n_scale-1000_dseg.label.gii
├── tpl-fsaverage_hemi-L_den-164k_atlas-Schaefer2018_seg-17n_scale-100_dseg.label.gii
├── tpl-fsaverage_hemi-L_den-164k_atlas-Schaefer2018_seg-17n_scale-200_dseg.label.gii
├── tpl-fsaverage_hemi-L_den-164k_atlas-Schaefer2018_seg-17n_scale-300_dseg.label.gii
├── tpl-fsaverage_hemi-L_den-164k_atlas-Schaefer2018_seg-17n_scale-400_dseg.label.gii
├── tpl-fsaverage_hemi-L_den-164k_atlas-Schaefer2018_seg-17n_scale-500_dseg.label.gii
├── tpl-fsaverage_hemi-L_den-164k_atlas-Schaefer2018_seg-17n_scale-600_dseg.label.gii
├── tpl-fsaverage_hemi-L_den-164k_atlas-Schaefer2018_seg-17n_scale-700_dseg.label.gii
├── tpl-fsaverage_hemi-L_den-164k_atlas-Schaefer2018_seg-17n_scale-800_dseg.label.gii
├── tpl-fsaverage_hemi-L_den-164k_atlas-Schaefer2018_seg-17n_scale-900_dseg.label.gii
├── tpl-fsaverage_hemi-L_den-164k_atlas-Schaefer2018_seg-7n_scale-1000_dseg.label.gii
├── tpl-fsaverage_hemi-L_den-164k_atlas-Schaefer2018_seg-7n_scale-100_dseg.label.gii
├── tpl-fsaverage_hemi-L_den-164k_atlas-Schaefer2018_seg-7n_scale-200_dseg.label.gii
├── tpl-fsaverage_hemi-L_den-164k_atlas-Schaefer2018_seg-7n_scale-300_dseg.label.gii
├── tpl-fsaverage_hemi-L_den-164k_atlas-Schaefer2018_seg-7n_scale-400_dseg.label.gii
├── tpl-fsaverage_hemi-L_den-164k_atlas-Schaefer2018_seg-7n_scale-500_dseg.label.gii
├── tpl-fsaverage_hemi-L_den-164k_atlas-Schaefer2018_seg-7n_scale-600_dseg.label.gii
├── tpl-fsaverage_hemi-L_den-164k_atlas-Schaefer2018_seg-7n_scale-700_dseg.label.gii
├── tpl-fsaverage_hemi-L_den-164k_atlas-Schaefer2018_seg-7n_scale-800_dseg.label.gii
├── tpl-fsaverage_hemi-L_den-164k_atlas-Schaefer2018_seg-7n_scale-900_dseg.label.gii
├── tpl-fsaverage_hemi-L_den-164k_atlas-Schaefer2018_seg-kong17n_scale-1000_dseg.label.gii
├── tpl-fsaverage_hemi-L_den-164k_atlas-Schaefer2018_seg-kong17n_scale-100_dseg.label.gii
├── tpl-fsaverage_hemi-L_den-164k_atlas-Schaefer2018_seg-kong17n_scale-200_dseg.label.gii
├── tpl-fsaverage_hemi-L_den-164k_atlas-Schaefer2018_seg-kong17n_scale-300_dseg.label.gii
├── tpl-fsaverage_hemi-L_den-164k_atlas-Schaefer2018_seg-kong17n_scale-400_dseg.label.gii
├── tpl-fsaverage_hemi-L_den-164k_atlas-Schaefer2018_seg-kong17n_scale-500_dseg.label.gii
├── tpl-fsaverage_hemi-L_den-164k_atlas-Schaefer2018_seg-kong17n_scale-600_dseg.label.gii
├── tpl-fsaverage_hemi-L_den-164k_atlas-Schaefer2018_seg-kong17n_scale-700_dseg.label.gii
├── tpl-fsaverage_hemi-L_den-164k_atlas-Schaefer2018_seg-kong17n_scale-800_dseg.label.gii
├── tpl-fsaverage_hemi-L_den-164k_atlas-Schaefer2018_seg-kong17n_scale-900_dseg.label.gii
├── tpl-fsaverage_hemi-L_den-164k_atlas-Yeo2011_seg-17n_dseg.label.gii
├── tpl-fsaverage_hemi-L_den-164k_atlas-Yeo2011_seg-7n_dseg.label.gii
├── tpl-fsaverage_hemi-L_den-164k_curv.shape.gii
├── tpl-fsaverage_hemi-L_den-164k_desc-std_sphere.surf.gii
├── tpl-fsaverage_hemi-L_den-164k_desc-vaavg_midthickness.shape.gii
├── tpl-fsaverage_hemi-L_den-164k_midthickness.surf.gii
├── tpl-fsaverage_hemi-L_den-164k_pial.surf.gii
├── tpl-fsaverage_hemi-L_den-164k_seg-aparc_desc-curated_dseg.label.gii
├── tpl-fsaverage_hemi-L_den-164k_seg-aparc_desc-original_dseg.label.gii
├── tpl-fsaverage_hemi-L_den-164k_sphere.surf.gii
├── tpl-fsaverage_hemi-L_den-164k_sulc.shape.gii
├── tpl-fsaverage_hemi-L_den-164k_white.surf.gii
├── tpl-fsaverage_hemi-L_den-3k_pial.surf.gii
├── tpl-fsaverage_hemi-L_den-3k_sphere.surf.gii
├── tpl-fsaverage_hemi-L_den-3k_white.surf.gii
├── tpl-fsaverage_hemi-L_den-41k_curv.shape.gii
├── tpl-fsaverage_hemi-L_den-41k_pial.surf.gii
├── tpl-fsaverage_hemi-L_den-41k_sphere.surf.gii
├── tpl-fsaverage_hemi-L_den-41k_sulc.shape.gii
├── tpl-fsaverage_hemi-L_den-41k_white.surf.gii
├── tpl-fsaverage_hemi-R_den-10k_curv.shape.gii
├── tpl-fsaverage_hemi-R_den-10k_pial.surf.gii
├── tpl-fsaverage_hemi-R_den-10k_sphere.surf.gii
├── tpl-fsaverage_hemi-R_den-10k_sulc.shape.gii
├── tpl-fsaverage_hemi-R_den-10k_white.surf.gii
├── tpl-fsaverage_hemi-R_den-164k_curv.shape.gii
├── tpl-fsaverage_hemi-R_den-164k_desc-std_sphere.surf.gii
├── tpl-fsaverage_hemi-R_den-164k_desc-vaavg_midthickness.shape.gii
├── tpl-fsaverage_hemi-R_den-164k_midthickness.surf.gii
├── tpl-fsaverage_hemi-R_den-164k_pial.surf.gii
├── tpl-fsaverage_hemi-R_den-164k_sphere.surf.gii
├── tpl-fsaverage_hemi-R_den-164k_sulc.shape.gii
├── tpl-fsaverage_hemi-R_den-164k_white.surf.gii
├── tpl-fsaverage_hemi-R_den-3k_pial.surf.gii
├── tpl-fsaverage_hemi-R_den-3k_sphere.surf.gii
├── tpl-fsaverage_hemi-R_den-3k_white.surf.gii
├── tpl-fsaverage_hemi-R_den-41k_curv.shape.gii
├── tpl-fsaverage_hemi-R_den-41k_pial.surf.gii
├── tpl-fsaverage_hemi-R_den-41k_sphere.surf.gii
├── tpl-fsaverage_hemi-R_den-41k_sulc.shape.gii
├── tpl-fsaverage_hemi-R_den-41k_white.surf.gii
├── tpl-fsaverage_res-01_T1w.nii.gz
├── tpl-fsaverage_res-01_den-41k_T1w.nii.gz
└── tpl-fsaverage_res-01_desc-brain_mask.nii.gz
```

As you can see, we have the Destrieux with the year in the atlas name:

```
├── tpl-fsaverage_hemi-L_den-164k_atlas-Destrieux2005_dseg.label.gii
├── tpl-fsaverage_hemi-L_den-164k_atlas-Destrieux2009_dseg.label.gii
```

We also have the different lausanne scales:

```
├── tpl-fsaverage_hemi-L_den-164k_atlas-Lausanne2018_scale-1_dseg.label.gii
├── tpl-fsaverage_hemi-L_den-164k_atlas-Lausanne2018_scale-2_dseg.label.gii
├── tpl-fsaverage_hemi-L_den-164k_atlas-Lausanne2018_scale-3_dseg.label.gii
├── tpl-fsaverage_hemi-L_den-164k_atlas-Lausanne2018_scale-4_dseg.label.gii
├── tpl-fsaverage_hemi-L_den-164k_atlas-Lausanne2018_scale-5_dseg.label.gii
```

And finally, Schaefer demonstrating seg- and scale- together:

```
├── tpl-fsaverage_hemi-L_den-164k_atlas-Schaefer2018_seg-17n_scale-1000_dseg.label.gii
├── tpl-fsaverage_hemi-L_den-164k_atlas-Schaefer2018_seg-17n_scale-100_dseg.label.gii
├── tpl-fsaverage_hemi-L_den-164k_atlas-Schaefer2018_seg-17n_scale-200_dseg.label.gii
├── tpl-fsaverage_hemi-L_den-164k_atlas-Schaefer2018_seg-17n_scale-300_dseg.label.gii
├── tpl-fsaverage_hemi-L_den-164k_atlas-Schaefer2018_seg-17n_scale-400_dseg.label.gii
├── tpl-fsaverage_hemi-L_den-164k_atlas-Schaefer2018_seg-17n_scale-500_dseg.label.gii
├── tpl-fsaverage_hemi-L_den-164k_atlas-Schaefer2018_seg-17n_scale-600_dseg.label.gii
├── tpl-fsaverage_hemi-L_den-164k_atlas-Schaefer2018_seg-17n_scale-700_dseg.label.gii
├── tpl-fsaverage_hemi-L_den-164k_atlas-Schaefer2018_seg-17n_scale-800_dseg.label.gii
├── tpl-fsaverage_hemi-L_den-164k_atlas-Schaefer2018_seg-17n_scale-900_dseg.label.gii
├── tpl-fsaverage_hemi-L_den-164k_atlas-Schaefer2018_seg-7n_scale-1000_dseg.label.gii
├── tpl-fsaverage_hemi-L_den-164k_atlas-Schaefer2018_seg-7n_scale-100_dseg.label.gii
├── tpl-fsaverage_hemi-L_den-164k_atlas-Schaefer2018_seg-7n_scale-200_dseg.label.gii
├── tpl-fsaverage_hemi-L_den-164k_atlas-Schaefer2018_seg-7n_scale-300_dseg.label.gii
├── tpl-fsaverage_hemi-L_den-164k_atlas-Schaefer2018_seg-7n_scale-400_dseg.label.gii
├── tpl-fsaverage_hemi-L_den-164k_atlas-Schaefer2018_seg-7n_scale-500_dseg.label.gii
├── tpl-fsaverage_hemi-L_den-164k_atlas-Schaefer2018_seg-7n_scale-600_dseg.label.gii
├── tpl-fsaverage_hemi-L_den-164k_atlas-Schaefer2018_seg-7n_scale-700_dseg.label.gii
├── tpl-fsaverage_hemi-L_den-164k_atlas-Schaefer2018_seg-7n_scale-800_dseg.label.gii
├── tpl-fsaverage_hemi-L_den-164k_atlas-Schaefer2018_seg-7n_scale-900_dseg.label.gii
├── tpl-fsaverage_hemi-L_den-164k_atlas-Schaefer2018_seg-kong17n_scale-1000_dseg.label.gii
├── tpl-fsaverage_hemi-L_den-164k_atlas-Schaefer2018_seg-kong17n_scale-100_dseg.label.gii
├── tpl-fsaverage_hemi-L_den-164k_atlas-Schaefer2018_seg-kong17n_scale-200_dseg.label.gii
├── tpl-fsaverage_hemi-L_den-164k_atlas-Schaefer2018_seg-kong17n_scale-300_dseg.label.gii
├── tpl-fsaverage_hemi-L_den-164k_atlas-Schaefer2018_seg-kong17n_scale-400_dseg.label.gii
├── tpl-fsaverage_hemi-L_den-164k_atlas-Schaefer2018_seg-kong17n_scale-500_dseg.label.gii
├── tpl-fsaverage_hemi-L_den-164k_atlas-Schaefer2018_seg-kong17n_scale-600_dseg.label.gii
├── tpl-fsaverage_hemi-L_den-164k_atlas-Schaefer2018_seg-kong17n_scale-700_dseg.label.gii
├── tpl-fsaverage_hemi-L_den-164k_atlas-Schaefer2018_seg-kong17n_scale-800_dseg.label.gii
├── tpl-fsaverage_hemi-L_den-164k_atlas-Schaefer2018_seg-kong17n_scale-900_dseg.label.gii
```

WDYT?

**Comment by oesteban** [comment]
Okay, I have @yasseraleman's verbal thumbs up. I'll go ahead and complete this with the right hemisphere and metadata.

**Comment by effigies** [comment]
I'm overall okay with this. I'm not really sure how these new entities will interact with BIDS, but I'm okay with figuring that out as use cases come up.

**Comment by oesteban** [comment]
Added default tsv files.

**Pull request merged**
