### PR TITLE
Add midthickness files

### PR DESCRIPTION
**Pull request by effigies**
Generated with mris_expand, manually edited to add secondary structure to correspond with white/pial surfaces.

Need to figure out how to push annexed objects to S3.

### CODE REVIEW

**Comment by effigies** [comment]
@oesteban Can you walk me through updating this early next week?

**Comment by oesteban** [comment]
Sure thing!

**Comment by effigies** [comment]
I forked the repo on gin and was able to push the annexed content there. https://gin.g-node.org/markiewicz/tpl-fsaverage/src/enh/add-midthickness

But I can't create a PR over there.

**Comment by oesteban** [comment]
I \*believe\* the PR should be here and a gha pushes the new blobs to gin

**Comment by effigies** [comment]
@oesteban Any chance of 30 minutes of your time today or Monday? I know you're working on a grant application, so it can wait until after if needed, but this is a bottleneck for an issue affecting both nibabies and fmriprep.

**Pull request merged**
